import exception.AmountException;
import exception.ClonesException;
import exception.DeadException;
import exception.FullException;
import humans.Aborigine;
import humans.Policeman;
import humans.Squatter;
import interactionWithHuman.Emotions;
import interactionWithHuman.Figurine;
import interactionWithHuman.Hallucinations;
import interactionWithHuman.Sound;
import nature.Bodies;
import nature.Bonfire;
import nature.Gallows;
import nature.Monolith;
import teams.TeamOfAborigines;
import teams.TeamOfPolicemen;
import transport.Car;
import transport.Waggon;
import war.War;
import world.Locations;
import world.World;
import result.Result;
public class Main{
	public static void main(String[] args) throws FullException, ClonesException, AmountException {
		World world = new World();
		world.setLocation(Locations.NEW_ORLEANS);
		Policeman p1 = new Policeman("Legress", 50);
		Policeman p2 = new Policeman("Joseph Galvez", 75, "Spain");
		Policeman p3 = new Policeman("Kate", 45, "France");
		Policeman p4 = new Policeman("Hopper", 70 );
		Policeman p5 = new Policeman("Jake", 60);
		Policeman p6 = new Policeman("Mike", 38, "USA");
		Policeman p7 = new Policeman("Thomas", 80, "UK");
		TeamOfPolicemen team2 = new TeamOfPolicemen(p1, p2, p3, p4, p5, p6, p7);
		world.addTeam(team2);
		Squatter s1 = new Squatter("Scott");
		world.addHuman(s1);
		s1.feel(Emotions.FEAR);
        Car car = new Car();
		Waggon waggon1 = new Waggon();
		Waggon waggon2 = new Waggon();
		team2.getIntoTpansport(car, waggon1, waggon2);
		s1.getIntoTpansport(car, waggon1, waggon2);
		car.go();
		waggon1.go();
		waggon2.go();
		world.setLocation(Locations.ROAD);
		car.arrive();
		waggon1.arrive();
		waggon2.arrive();
		world.setLocation(Locations.FOREST);
        Aborigine a1 = new Aborigine(world, "Alex", 40, "Portugal");
		Aborigine a2 = new Aborigine(world, "Luke", 50, "India");
		Aborigine a3 = new Aborigine(world, "Daniel", 40, "Brazil");
		Aborigine a4 = new Aborigine(world, "Mike", 20);
		Aborigine a5 = new Aborigine(world, "Simon", 60);
		Aborigine a6 = new Aborigine(world, "Jacob", 70, "Morocco");
		Aborigine a7 = new Aborigine(world, "Nicholas", 40, "Brazil");
		TeamOfAborigines team1 = new TeamOfAborigines(a1, a2, a3, a4, a5, a6, a7);
		Bonfire bonfire = new Bonfire();
		bonfire.burn(team1);
		Monolith monolith = new Monolith("granite", 8);
		monolith.riseUp();
		Figurine figurine = new Figurine();
		figurine.setPlace("on the top of monolith");
		Gallows gallows = new Gallows(10);
		gallows.locate();
		Bodies bodies = new Bodies();
		bodies.hangDown(gallows);
	    Sound sound = new Sound("forest");
        p2.hear(sound);
        Hallucinations hallucinations = new Hallucinations("weak beating of large wings, and also the reflection of sparkling eyes and the outline of a huge white mass behind the very distant trees");
        p2.see(hallucinations);
        team2.feel(Emotions.STUPOR);
        team2.feel(Emotions.COURAGE);
	    War war = new War(team1, team2);
		war.go();
		world.setLocation(Locations.POLICE_STATION);
		Result result = new Result();
		result.show(war);
	    try{
          p1.take(figurine);
	    } catch (DeadException err) {
          System.out.println(err.getMessage());
	    }
    }
}